/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library;

import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author mario
 */
public class NewJFrame2 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public NewJFrame2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLabel1_id = new javax.swing.JLabel();
        jLabel2_name = new javax.swing.JLabel();
        jLabel3_password = new javax.swing.JLabel();
        jLabel4_email = new javax.swing.JLabel();
        jTextField1_id = new javax.swing.JTextField();
        jTextField2_name = new javax.swing.JTextField();
        jTextField3_password = new javax.swing.JTextField();
        jTextField4_email = new javax.swing.JTextField();
        jButton1_submit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1_id.setText("ID");

        jLabel2_name.setText("name ");

        jLabel3_password.setText("password");

        jLabel4_email.setText("email");

        jTextField1_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_idActionPerformed(evt);
            }
        });

        jTextField2_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2_nameActionPerformed(evt);
            }
        });

        jTextField3_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3_passwordActionPerformed(evt);
            }
        });

        jButton1_submit.setText("Submit");
        jButton1_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4_email)
                                .addComponent(jLabel3_password)
                                .addComponent(jLabel2_name)
                                .addComponent(jTextField3_password, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                .addComponent(jTextField4_email))
                            .addComponent(jLabel1_id)
                            .addComponent(jTextField1_id, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2_name, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jButton1_submit)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1_id)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3_password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4_email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jButton1_submit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3_passwordActionPerformed

    private void jTextField1_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_idActionPerformed

    private void jTextField2_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2_nameActionPerformed

    //Submit Button
    private void jButton1_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_submitActionPerformed
        // TODO add your handling code here:
        String  id    = jTextField1_id.getText();
        String  name  = jTextField2_name.getText();
        String  pass  = jTextField3_password.getText();
        String  email = jTextField4_email.getText();
        
       
        PreparedStatement pstmt = null;
        try{
             DBConnect c = new DBConnect();
             Connection con = c.DBConnect();
          
            // test cases  for insert  
            //----------------------------------------------
            // admin  name , pass , email (accepted)
            //int i = c.Insert_Admin("test2", "admin2", "case2@gmail.com");
             
            // student name , pass , email   (accepted)
            //int j = c.Insert_Student("test2" , "student2", "case2", "test2");

            // bookname,author,quantity,sellable,price (accepted)
            //int k = c.Insert_Book("test2", "case2", 10, "not2" , 30.6);
            //----------------------------------------------

            
            // test cases for Delete 
            //----------------------------------------------
            // admin delete (accepted)
            //int i = c.Delete_admin(12); 
            
            // delete student(accepted) 
            //int j = c.Delete_student(3);
            
            // delete book (accepted)
            //int k = c.Delete_book(5);
            //---------------------------------------------- 
           
             
            // test case for update  
            //----------------------------------------------
            // update admin (accepted)
            //int i = c.Update_admin(9,"test_name", "test_pass", "test_email");
            
            // update student (accepted)
            //int i = c.Update_student(1, "test_student", "student_pass","test_email", "test_phone");
            
            // update book (accpeted)
            // code, name,  author,  qunatity, sellable , price 
            //int i = c.Update_book(1, "test_name", "test_author" , 50, "yes bae",1593.34);
            //----------------------------------------------
            
            
            //test case for login admin  (accepted)
            //int i = c.login_admin(email,pass);
            //----------------------------------------------
                     
            // test case for login student  (accepted)
            //int i = c.login_student("no","test");
            //----------------------------------------------
            
            
            //test case for update book Quantity (accepted)
            //int i = c.update_quantity(1,5);
            
            // test case for order book (accepted)
            //int i = c.order_Book(1, 1, 1, "fda");
            //----------------------------------------------
            
            //test case for borrow book (accepted)
            //int i = c.borrow_Book(1,1, "45");
            //----------------------------------------------
           
            //test case for return book 
            //int i = c.return_book(1);
            
  /*          
    int j = 1 , k = 1; 

   System.out.println("i = "+i);
    if(i>0 && j>0 && k>0){
        JOptionPane.showMessageDialog(null, "Transaction is Executed");
    }else{
        JOptionPane.showMessageDialog(null, "Transaction failed to execute");
    }


    */        
            
            //test case for select 
            //----------------------------------------------
            
            System.out.println("\n*****************************************\n");
            
            // select all admins (accepted)
            c.Select_admin();
             
            System.out.println("\n*****************************************\n");
             
            // select all students (accepted)
            c.Select_student();
             
            System.out.println("\n*****************************************\n");
             
            // select all books (accepted)
            c.Select_book();
            
            System.out.println("\n*****************************************\n");
            
            // view borrows (accepted)
            c.view_borrows();
            
            System.out.println("\n*****************************************\n");
            
            //view orders   (accepted)
            c.view_orders();
            
            System.out.println("\n*****************************************\n");
            
            // view book codes (accepted)
            c.book_codes();
            
            System.out.println("\n*****************************************\n");
            
            // books with name (accepted)
            c.Search_book("bookn");
           
            
            System.out.println("\n*****************************************\n");
                     
           //----------------------------------------------
            
            
            
           System.out.println("Execution  Success");
        }catch(SQLException ex){
            System.out.println("Error in Connection "+ex);
        }
        
    }//GEN-LAST:event_jButton1_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_submit;
    private javax.swing.JLabel jLabel1_id;
    private javax.swing.JLabel jLabel2_name;
    private javax.swing.JLabel jLabel3_password;
    private javax.swing.JLabel jLabel4_email;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1_id;
    private javax.swing.JTextField jTextField2_name;
    private javax.swing.JTextField jTextField3_password;
    private javax.swing.JTextField jTextField4_email;
    // End of variables declaration//GEN-END:variables
}

